In [7]:
#Basic import

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#Modelling
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

ModuleNotFoundError: No module named 'kiwisolver._cext'

Import the CSV Data as Pandas DataFrame

In [2]:
import sys
print(sys.executable)

c:\Users\Nidhi Mehta\OneDrive\Desktop\ML Project\venv\Scripts\python.exe

In [3]:
import PIL
print(PIL.__version__)

10.2.0

In [1]:
import matplotlib.pyplot as plt

plt.plot([1,2,3], [4,5,6])
plt.show()

ModuleNotFoundError: No module named 'kiwisolver._cext'

In [8]:
df= pd.read_csv('data/raw.csv')

In [9]:
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic_group,age,english_grade,math_grade,sciences_grade,language_grade,portfolio_rating,coverletter_rating,refletter_rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4.0,4.0,4.0
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5.0,4.0,5.0
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3.0,3.0,4.0
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5.0,2.0,4.0
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4.0,4.0,5.0

Preparing X and Y variables

In [10]:
X= df.drop(columns=['math_grade'],axis=1)

In [11]:
X.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic_group,age,english_grade,sciences_grade,language_grade,portfolio_rating,coverletter_rating,refletter_rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.1,1.0,4.0,4.0,4.0
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.6,5.0,5.0,4.0,5.0
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.2,5.0,3.0,3.0,4.0
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,3.2,5.0,5.0,2.0,4.0
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,3.4,1.0,4.0,4.0,5.0

In [12]:
print("Categories in 'gender' variable:",end=" ")
print(df['gender'].unique())

Categories in 'gender' variable: ['F' 'M' 'other']

In [13]:
y=df['math_grade']

In [14]:
y

0      3.7
1      3.2
2      3.8
3      2.8
4      2.6
      ...
302    3.7
303    3.9
304    3.4
305    2.8
306    3.2
Name: math_grade, Length: 307, dtype: float64

In [16]:
#Create transformer with 3 types of transformers

num_features=X.select_dtypes(exclude="object").columns
cat_features=X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

nummeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",nummeric_transformer,num_features),
    ]
)

ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.